-- Trading Platform Database Schema
-- PostgreSQL 15+

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

-- Custom Types
CREATE TYPE public.order_status AS ENUM (
    'new',
    'open',
    'partially_filled',
    'filled',
    'canceled',
    'rejected'
);

CREATE TYPE public.order_type AS ENUM (
    'market',
    'limit',
    'stop',
    'stop_limit'
);

CREATE TYPE public.trade_side AS ENUM (
    'buy',
    'sell'
);

-- Assets Table
CREATE TABLE public.assets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(32) NOT NULL UNIQUE,
    name character varying(64) NOT NULL
);

-- Exchanges Table
CREATE TABLE public.exchanges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(32) NOT NULL UNIQUE,
    name character varying(64) NOT NULL
);

-- Users Table
CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255) NOT NULL UNIQUE,
    display_name character varying(100),
    password_hash text,
    is_active boolean DEFAULT true NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Symbols Table
CREATE TABLE public.symbols (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol character varying(32) NOT NULL UNIQUE,
    base_asset_id bigint NOT NULL REFERENCES public.assets(id),
    quote_asset_id bigint NOT NULL REFERENCES public.assets(id),
    is_active boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_symbols_assets_diff CHECK (base_asset_id <> quote_asset_id)
);

-- Strategies Table
CREATE TABLE public.strategies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name character varying(100) NOT NULL,
    description text,
    params_json jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Exchange Accounts Table
CREATE TABLE public.exchange_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    exchange_id bigint NOT NULL REFERENCES public.exchanges(id),
    name character varying(100),
    api_key text NOT NULL,
    api_secret text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    meta_json jsonb,
    CONSTRAINT uq_exchange_accounts UNIQUE (user_id, exchange_id, name)
);

-- Portfolios Table
CREATE TABLE public.portfolios (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name character varying(100) NOT NULL,
    base_currency_id bigint NOT NULL REFERENCES public.assets(id),
    exchange_account_id bigint REFERENCES public.exchange_accounts(id),
    strategy_id bigint REFERENCES public.strategies(id),
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX ix_portfolios_user_id ON public.portfolios USING btree (user_id);

-- Portfolio Symbols Table
CREATE TABLE public.portfolio_symbols (
    portfolio_id bigint NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
    symbol_id bigint NOT NULL REFERENCES public.symbols(id) ON DELETE CASCADE,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (portfolio_id, symbol_id)
);

-- Balances Table
CREATE TABLE public.balances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
    asset_id bigint NOT NULL REFERENCES public.assets(id),
    qty numeric(38,18) DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_balances_qty CHECK (qty >= 0),
    CONSTRAINT uq_balances UNIQUE (portfolio_id, asset_id)
);

CREATE INDEX ix_balances_portfolio ON public.balances USING btree (portfolio_id);

-- Orders Table
CREATE TABLE public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
    symbol_id bigint NOT NULL REFERENCES public.symbols(id),
    exchange_id bigint NOT NULL REFERENCES public.exchanges(id),
    external_order_id character varying(64),
    side public.trade_side NOT NULL,
    type public.order_type NOT NULL,
    price numeric(20,8),
    quantity numeric(38,18) NOT NULL,
    status public.order_status DEFAULT 'new' NOT NULL,
    created_ts timestamp with time zone DEFAULT now() NOT NULL,
    updated_ts timestamp with time zone DEFAULT now() NOT NULL,
    meta_json jsonb,
    CONSTRAINT chk_orders_quantity_pos CHECK (quantity > 0)
);

CREATE INDEX ix_orders_portfolio ON public.orders USING btree (portfolio_id, created_ts);
CREATE INDEX ix_orders_symbol ON public.orders USING btree (symbol_id, created_ts);

-- Positions Table
CREATE TABLE public.positions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
    symbol_id bigint NOT NULL REFERENCES public.symbols(id) ON DELETE CASCADE,
    qty numeric(38,18) DEFAULT 0 NOT NULL,
    avg_price numeric(38,18),
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_positions_qty CHECK (qty >= 0),
    CONSTRAINT uq_positions UNIQUE (portfolio_id, symbol_id)
);

CREATE INDEX ix_positions_portfolio ON public.positions USING btree (portfolio_id);
CREATE INDEX ix_positions_portfolio_symbol ON public.positions USING btree (portfolio_id, symbol_id);

-- Trades Table (Partitioned by month)
CREATE TABLE public.trades (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id bigint NOT NULL,
    symbol_id bigint NOT NULL,
    exchange_id bigint NOT NULL,
    order_id bigint,
    external_trade_id character varying(64) NOT NULL,
    side public.trade_side NOT NULL,
    price numeric(20,8) NOT NULL,
    quantity numeric(38,18) NOT NULL,
    notional numeric(38,18) GENERATED ALWAYS AS (price * quantity) STORED,
    fee_asset_id bigint,
    fee_amount numeric(38,18),
    fee_notional numeric(38,18) GENERATED ALWAYS AS (
        CASE WHEN (fee_asset_id IS NOT NULL AND fee_amount IS NOT NULL)
        THEN fee_amount ELSE NULL END
    ) STORED,
    trade_ts timestamp with time zone NOT NULL,
    processing_ts timestamp with time zone DEFAULT now() NOT NULL,
    source_date_partition bigint,
    raw_source character varying(32),
    meta_json jsonb,
    PRIMARY KEY (id, trade_ts),
    CONSTRAINT chk_trades_price_pos CHECK (price > 0),
    CONSTRAINT chk_trades_quantity_pos CHECK (quantity > 0)
) PARTITION BY RANGE (trade_ts);

-- Create partitions for 2025
CREATE TABLE public.trades_2025_01 PARTITION OF public.trades
    FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');

CREATE TABLE public.trades_2025_02 PARTITION OF public.trades
    FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');

CREATE TABLE public.trades_2025_03 PARTITION OF public.trades
    FOR VALUES FROM ('2025-03-01') TO ('2025-04-01');

CREATE TABLE public.trades_2025_04 PARTITION OF public.trades
    FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');

CREATE TABLE public.trades_2025_05 PARTITION OF public.trades
    FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');

CREATE TABLE public.trades_2025_06 PARTITION OF public.trades
    FOR VALUES FROM ('2025-06-01') TO ('2025-07-01');

CREATE TABLE public.trades_2025_07 PARTITION OF public.trades
    FOR VALUES FROM ('2025-07-01') TO ('2025-08-01');

CREATE TABLE public.trades_2025_08 PARTITION OF public.trades
    FOR VALUES FROM ('2025-08-01') TO ('2025-09-01');

CREATE TABLE public.trades_2025_09 PARTITION OF public.trades
    FOR VALUES FROM ('2025-09-01') TO ('2025-10-01');

CREATE TABLE public.trades_2025_10 PARTITION OF public.trades
    FOR VALUES FROM ('2025-10-01') TO ('2025-11-01');

CREATE TABLE public.trades_2025_11 PARTITION OF public.trades
    FOR VALUES FROM ('2025-11-01') TO ('2025-12-01');

CREATE TABLE public.trades_2025_12 PARTITION OF public.trades
    FOR VALUES FROM ('2025-12-01') TO ('2026-01-01');

-- Trades indexes
CREATE INDEX ix_trades_portfolio_ts ON public.trades (portfolio_id, trade_ts);
CREATE INDEX ix_trades_symbol_ts ON public.trades (symbol_id, trade_ts);
CREATE INDEX ix_trades_exchange_symbol_ts ON public.trades (exchange_id, symbol_id, trade_ts);
CREATE UNIQUE INDEX uq_trades_exchange_external ON public.trades (exchange_id, external_trade_id, trade_ts);

-- OHLCV Table
CREATE TABLE public.ohlcv_1m (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol_id bigint NOT NULL REFERENCES public.symbols(id),
    exchange_id bigint NOT NULL REFERENCES public.exchanges(id),
    open_ts timestamp with time zone NOT NULL,
    open numeric(20,8) NOT NULL,
    high numeric(20,8) NOT NULL,
    low numeric(20,8) NOT NULL,
    close numeric(20,8) NOT NULL,
    volume numeric(38,18),
    CONSTRAINT uq_ohlcv_1m UNIQUE (symbol_id, exchange_id, open_ts)
);

CREATE INDEX ix_ohlcv_symbol_ts ON public.ohlcv_1m (symbol_id, open_ts);
CREATE INDEX ix_ohlcv_1m_symbol_time ON public.ohlcv_1m (symbol_id, exchange_id, open_ts);

-- Portfolio Equity Snapshots
CREATE TABLE public.portfolio_equity_snapshots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id bigint NOT NULL REFERENCES public.portfolios(id) ON DELETE CASCADE,
    snapshot_ts timestamp with time zone NOT NULL,
    equity_base numeric(38,18) NOT NULL,
    realized_pnl numeric(38,18),
    unrealized_pnl numeric(38,18),
    meta_json jsonb,
    CONSTRAINT uq_portfolio_equity_unique UNIQUE (portfolio_id, snapshot_ts)
);

CREATE INDEX ix_equity_portfolio_ts ON public.portfolio_equity_snapshots (portfolio_id, snapshot_ts);

-- Audit Events
CREATE TABLE public.audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES public.users(id) ON DELETE SET NULL,
    portfolio_id bigint REFERENCES public.portfolios(id) ON DELETE SET NULL,
    event_type character varying(64) NOT NULL,
    event_ts timestamp with time zone DEFAULT now() NOT NULL,
    details jsonb
);

CREATE INDEX ix_audit_user_ts ON public.audit_events (user_id, event_ts);

-- Materialized Views for aggregated OHLCV
CREATE MATERIALIZED VIEW public.ohlcv_5m AS
WITH buckets AS (
    SELECT
        symbol_id,
        exchange_id,
        open_ts,
        open,
        high,
        low,
        close,
        volume,
        date_trunc('minute', open_ts) -
        ((EXTRACT(minute FROM open_ts)::integer % 5)::double precision * interval '1 minute') AS bucket_ts
    FROM public.ohlcv_1m
)
SELECT
    symbol_id,
    exchange_id,
    bucket_ts,
    min(open_ts) AS first_ts,
    (array_agg(open ORDER BY open_ts))[1] AS open,
    max(high) AS high,
    min(low) AS low,
    (array_agg(close ORDER BY open_ts DESC))[1] AS close,
    sum(volume) AS volume
FROM buckets
GROUP BY symbol_id, exchange_id, bucket_ts
WITH NO DATA;

CREATE UNIQUE INDEX uq_ohlcv_5m ON public.ohlcv_5m (symbol_id, exchange_id, bucket_ts);

-- Apache Iceberg Catalog Tables
-- These tables are required for PyIceberg SQL catalog to store metadata

CREATE TABLE IF NOT EXISTS public.iceberg_tables (
    catalog_name VARCHAR(255) NOT NULL,
    table_namespace VARCHAR(255) NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    metadata_location TEXT NOT NULL,
    previous_metadata_location TEXT,
    PRIMARY KEY (catalog_name, table_namespace, table_name)
);

CREATE TABLE IF NOT EXISTS public.iceberg_namespace_properties (
    catalog_name VARCHAR(255) NOT NULL,
    namespace VARCHAR(255) NOT NULL,
    property_key VARCHAR(255) NOT NULL,
    property_value VARCHAR(255) NOT NULL,
    PRIMARY KEY (catalog_name, namespace, property_key)
);

-- Insert initial data
INSERT INTO public.assets (code, name) VALUES
    ('BTC', 'Bitcoin'),
    ('ETH', 'Ethereum'),
    ('USDT', 'Tether'),
    ('BNB', 'Binance Coin'),
    ('USD', 'US Dollar');

INSERT INTO public.exchanges (code, name) VALUES
    ('BINANCE', 'Binance'),
    ('COINBASE', 'Coinbase'),
    ('KRAKEN', 'Kraken');

-- Create default symbols
INSERT INTO public.symbols (symbol, base_asset_id, quote_asset_id) VALUES
    ('BTCUSDT', (SELECT id FROM public.assets WHERE code = 'BTC'), (SELECT id FROM public.assets WHERE code = 'USDT')),
    ('ETHUSDT', (SELECT id FROM public.assets WHERE code = 'ETH'), (SELECT id FROM public.assets WHERE code = 'USDT')),
    ('BNBUSDT', (SELECT id FROM public.assets WHERE code = 'BNB'), (SELECT id FROM public.assets WHERE code = 'USDT'));
